### ISSUE TITLE
Using OpenAI Embeddings with `get_embedding_function.py`

### ISSUE THREAD

**Issue by janduplessis883** [pixegami/rag-tutorial-v2#1]
HI Great video, I am trying to use OpenAI Embedding and keep running into a problem, can you help?

```
from openai import OpenAI
import os

client = OpenAI()

def get_embedding_function(text, model="text-embedding-3-small"):
   text = text.replace("\n", " ")
   return client.embeddings.create(input = [text], model=model).data[0].embedding
```

This is my updated code for the `get_embedding_function.py` script.

The embedding need input but i cannot see it being passed to it in the script in `populate_database.py`

**Thanks in advance 😀 Jan**

**Comment by jaimeelincoln** [comment]
I used something like the below - you have to update the 'embedding_function' variable in query_data.py with the model argument to get it to work though. I've pasted both below

def get_embedding_function():
    embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

    return embeddings
    
    
    in query_data.py
    embedding_function = OpenAIEmbeddings(model="text-embedding-3-large")

**Comment by pixegami** [comment]
Yup, as @jaimeelincoln says, you can use the OpenAI embedding helper function directly rather than having to do it via the client: 

https://python.langchain.com/v0.1/docs/integrations/text_embedding/openai/

```
OpenAIEmbeddings(model="text-embedding-3-large")
```

**Comment by pixegami** [comment]
> The embedding need input but i cannot see it being passed to it in the script in populate_database.py

Also, your code is trying to create the actual embedding itself, which is why you need the input (text and model). But `get_embedding_function` is supposed to return the *function/class* for embedding (which is what something like the `OpenAIEmbeddings` class does).
