### ISSUE TITLE
Embedding failed

### ISSUE THREAD

**Issue by kuanlinhuang** [pixegami/rag-tutorial-v2#2]
Followed the example & embedding is not working (give back empty sources)

If anyone has any clue would really appreciate it!

**Comment by mohamedamara1** [comment]
make sure you run the populate_database file before running query_data

**Comment by amine-sabbahi** [comment]
what a genius :)

**Comment by mohamedamara1** [comment]
> what a genius :)

It's a mistake that can happen (I did it), there's no need to be rude about it.
Learn how to appreciate it when someone tries to help.

**Comment by pixegami** [comment]
Thanks for sharing the solution! Yup, you need to run `populate_database` first before the embeddings work. Please re-open this if you felt the issue hasn't been resolved!
